excluded:
  - Pods
  - wallabag/Model/Server.swift
  - wallabag/Lib/CoreData.swift 
  - wallabag/Entity/Entry+CoreDataProperties.swift
  - wallabag/Entity/Entry+CoreDataClass.swift
line_length: 300
identifier_name:
  excluded:
    - id
    - to
    - at
